/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.example.dominio.Consultor;
import com.example.dominio.Empresa;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class JFPrincipal extends javax.swing.JFrame {
    private Empresa emp;

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        //jbConsultar.addActionListener(new EscuchaBoton());
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        buttonGroup1.add(jrbNombre);
        buttonGroup1.add(jrbPuesto);
        jrbNombre.setSelected(true);
        jbAgregar.setMnemonic('A');
        jbConsultar.setMnemonic('C');

        this.setLocationRelativeTo(null);
        this.setTitle("Empleados Empresa SOFT");
        emp = new Empresa();

        emp.agregarEmpleado(new Consultor(100, 300, 1, "Juan", "01/01/2010", "Desarrollador Jr"));
        emp.agregarEmpleado(new Consultor(100, 300, 1, "Zoilo L", "01/01/2015", "Analista Sr"));

        jtaNomina.setText(emp.mostrarNomina(1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaNomina = new javax.swing.JTextArea();
        jbConsultar = new javax.swing.JButton();
        jrbNombre = new javax.swing.JRadioButton();
        jrbPuesto = new javax.swing.JRadioButton();
        jbAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("NOMINA DE EMPLEADOS");

        jtaNomina.setEditable(false);
        jtaNomina.setColumns(20);
        jtaNomina.setRows(5);
        jScrollPane1.setViewportView(jtaNomina);

        jbConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbConsultar.setText("Consultar");
        jbConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbConsultarMouseClicked(evt);
            }
        });
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        jrbNombre.setText("Nombre");

        jrbPuesto.setText("Puesto");

        jbAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jrbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbPuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConsultar)
                    .addComponent(jrbNombre)
                    .addComponent(jrbPuesto)
                    .addComponent(jbAgregar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        String nomina = null;
        if (jrbNombre.isSelected()) {
            nomina = emp.mostrarNomina(1);
        } else {
            nomina = emp.mostrarNomina(2);
        }
        jtaNomina.setText(nomina);
    }//GEN-LAST:event_jbConsultarActionPerformed

    private void jbConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbConsultarMouseClicked
        JOptionPane.showMessageDialog(this, "Hola!");
    }//GEN-LAST:event_jbConsultarMouseClicked

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
       JDNuevoTrabajador child =  new JDNuevoTrabajador(this, true, emp);
       child.setLocationRelativeTo(null);
       child.setTitle("Alta de Trabajador");
       child.setVisible(true);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcion = JOptionPane.showConfirmDialog(this,"Seguro que desea salir?", "Aviso", JOptionPane.YES_NO_OPTION );
        if(opcion == JOptionPane.YES_OPTION)
           System.exit(0);
       
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbPuesto;
    private javax.swing.JTextArea jtaNomina;
    // End of variables declaration//GEN-END:variables

    class EscuchaBoton implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent ae) {
            JOptionPane.showMessageDialog(null, "Este es un escucha PICANTE!", "Aviso", JOptionPane.QUESTION_MESSAGE);
        }
    }
}
